@startuml CerrarSesion
title Cerrar Sesión
left to right direction

actor Usuario

rectangle "Sistema de Conciliaciones Bancarias" {
    Usuario -> (Solicitar Cerrar Sesión)
    (Solicitar Cerrar Sesión) --> (Confirmar Cierre)
    (Confirmar Cierre) --> (Terminar Sesión)
    (Terminar Sesión) --> Usuario : Sesión cerrada
}

@enduml