@startuml ConciliacionBancaria
title Conciliación Bancaria
left to right direction

actor Administrador as admin
actor "Base de Datos" as db

rectangle "Sistema de Conciliaciones Bancarias" {
    admin --> (Iniciar Conciliación)

    (Iniciar Conciliación) --> (Obtener Extracto Bancario)
    (Obtener Extracto Bancario) --> db

    (Iniciar Conciliación) --> (Obtener Registros Contables)
    (Obtener Registros Contables) --> db

    (Iniciar Conciliación) --> (Comparar Transacciones)

    (Comparar Transacciones) --> (Generar Informe)
    (Generar Informe) --> admin
}

@enduml