@startuml GestionarUsuarios
title Gestionar Usuarios
left to right direction

actor Administrador as admin
actor "Base de Datos" as db
' checar si esta bien asi o como gestionar cuenta bancaria
rectangle "Sistema de Conciliaciones Bancarias" {
    admin --> (Seleccionar Acción)

    (Seleccionar Acción) --> (Agregar Usuario) 
    (Seleccionar Acción) --> (Modificar Usuario) 
    (Seleccionar Acción) --> (Eliminar Usuario) 

    ' (Seleccionar Acción) --> (Ingresar Datos) 
    (Ingresar Datos) --> (Validar Datos)
    '  --> (Guardar Datos)

    ' (Validar Datos
    (Agregar Usuario) --> (Ingresar Datos)
    (Modificar Usuario) --> (Ingresar Datos)
    (Eliminar Usuario) --> (Ingresar Datos)

    (Validar Datos) --> (Guardar Datos) 
    (Guardar Datos) --> db
}

@enduml
