@startuml GestionarIngresosEgresos
title Gestionar Ingresos y Egresos
left to right direction

actor Administrador as admin
actor Auditor as auditor
actor "Base de Datos" as db

rectangle "Sistema de Conciliaciones Bancarias" {
    admin --> (Seleccionar Acción)
    auditor --> (Seleccionar Acción)

    (Seleccionar Acción) --> (Registrar Ingreso)
    (Seleccionar Acción) --> (Registrar Egreso)
    (Seleccionar Acción) --> (Modificar Ingreso)
    (Seleccionar Acción) --> (Modificar Egreso)
    (Seleccionar Acción) --> (Eliminar Ingreso)
    (Seleccionar Acción) --> (Eliminar Egreso)

    (Registrar Ingreso) --> (Ingresar Datos)
    (Registrar Egreso) --> (Ingresar Datos)
    (Modificar Ingreso) --> (Seleccionar Ingreso)
    (Modificar Egreso) --> (Seleccionar Egreso)
    (Eliminar Ingreso) --> (Seleccionar Ingreso)
    (Eliminar Egreso) --> (Seleccionar Egreso)

    (Ingresar Datos) --> (Validar Datos)
    (Validar Datos) --> (Guardar Datos)
    (Validar Datos) --> db
    (Guardar Datos) --> db

    (Seleccionar Ingreso) --> (Modificar Datos)
    (Modificar Datos) --> (Validar Datos)

    (Seleccionar Egreso) --> (Modificar Datos)
    (Modificar Datos) --> (Validar Datos)

    (Seleccionar Ingreso) --> (Confirmar Eliminación)
    (Seleccionar Egreso) --> (Confirmar Eliminación)
    (Confirmar Eliminación) --> (Eliminar Datos)
    (Eliminar Datos) --> db
}

@enduml