@startuml IniciarSesion
title Iniciar Sesión

actor Usuario
actor Administrador as admin
actor Auditor as auditor

rectangle "Sistema de Conciliaciones Bancarias" {
    Usuario -> (Ingresar Datos)
    (Ingresar Datos) -> (Validar Credenciales)
    (Validar Credenciales) --> (Asignar Sesión Activa)

    (Asignar Sesión Activa) --> admin : Si es Administrador
    (Asignar Sesión Activa) --> auditor : Si es Auditor
}

@enduml
