@startuml IniciarSesion
title Iniciar Sesión
left to right direction

actor Usuario
actor Administrador as admin
actor Auditor as auditor

rectangle "Sistema de Conciliaciones Bancarias" {
    Usuario -> (Ingresar Credenciales)
    (Ingresar Credenciales) --> (Validar Credenciales)
    (Validar Credenciales) --> (Acceso Permitido)
    (Validar Credenciales) --> (Acceso Denegado)
    (Acceso Permitido) --> admin : Si es Administrador
    (Acceso Permitido) --> auditor : Si es Auditor
    (Acceso Denegado) --> Usuario : Mostrar error
}

@enduml