@startuml IniciarSesion
title Iniciar Sesión

actor Usuario
actor Administrador as admin
actor Auditor as auditor

rectangle "Sistema de Conciliaciones Bancarias" {
    Usuario -> (Iniciar Sesión) : Credenciales

    (Iniciar Sesión) -> (Validar Credenciales)
    (Iniciar Sesión) --> (Asignar Sesión Activa)

    (Validar Credenciales) --> (Mostrar Mensaje de Error) : Si falla
    (Asignar Sesión Activa) --> (Mostrar Menú de Usuario) : Segun Rol

    (Validar Credenciales) -> admin : Si es Administrador
    (Validar Credenciales) -> auditor : Si es Auditor
}

@enduml
