@startuml LibroContable
title Libro Contable
left to right direction

actor Administrador as admin
actor "Base de Datos" as db

rectangle "Sistema de Conciliaciones Bancarias" {
    admin --> (Consultar Libro Contable)

    (Consultar Libro Contable) --> (Obtener Transacciones)
    (Obtener Transacciones) --> db

    (Obtener Transacciones) --> (Mostrar Transacciones)
    (Mostrar Transacciones) --> admin

    admin --> (Generar Reporte)
    (Generar Reporte) --> (Seleccionar Formato)
    (Seleccionar Formato) --> (Exportar Reporte)
}

@enduml